[build]
  publish = "dist"  # Directory to publish (e.g., for React, it might be "build" or "dist")
  command = "npm run build"  # Build command

[[redirects]]
  from = "/old-path/*"
  to = "/new-path/:splat"
  status = 301  # Permanent redirect
  force = true  # Force the redirect

[functions]
  directory = "functions"  # Directory for Netlify functions

[headers]
  /* Custom headers */
  /* Key-value pairs can be added here */
